import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/theme/theme-provider"
import MainMenu, { type MenuItem } from "~/components/menu/mainMenu";
import { Home } from "lucide-react"

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const menuItems: MenuItem[] = [
    {
        path: "/",
        description: <Home />
    }
]

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable}`} suppressHydrationWarning>
            <body>
                <TRPCReactProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <header>
                            <MainMenu menuItems={menuItems} />
                        </header>
                        <main>
                            {children}
                        </main>
                    </ThemeProvider>
                </TRPCReactProvider>
            </body>
        </html>
    );
}
