import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/theme/theme-provider"
import MainMenu, { type MenuItem } from "~/components/menu/mainMenu";
import { Home } from "lucide-react"
import { TooltipProvider } from "~/components/ui/tooltip";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const menuItems: MenuItem[] = [
    {
        path: "/",
        description: <Home />
    },
    {
        path: "/playground",
        description: "Playground"
    }
]

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable} h-full`} suppressHydrationWarning>
            <body className="h-full flex flex-col">
                <TRPCReactProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <TooltipProvider>
                            <header>
                                <MainMenu menuItems={menuItems} />
                            </header>
                            <main className="flex-grow p-2">
                                {children}
                            </main>                            
                        </TooltipProvider>
                    </ThemeProvider>
                </TRPCReactProvider>
            </body>
        </html>
    );
}
